export const phrases = [
  "Você não tem um ticket dourado para este passeio!",
  "Nem o gatinho entende como você chegou aqui!",
  "Essa página não é o que você procura... vá para casa!",
  "O gatinho disse que você precisa de um mapa!",
  "Esse acesso é restrito até para o gatinho!",
  "Acesso negado! O gatinho está de guarda!",
  "Você não está no nível suficiente para entrar aqui!",
  "O gatinho fez um check-up e você não passou!",
  "Essa página é só para os felinos mais legais!",
  "O gatinho disse que só entra quem tem muitos mimos!",
  "Você se perdeu no labirinto de gatinhos!",
  "Parece que você pisou no rabo do gatinho sem querer!",
  "Desculpe, mas o gatinho está de olho na lista de convidados!",
  "Ei! Você não pode passar!",
  "Meow! Isso não é permitido!",
  "Você se perdeu, humano!",
  "Não me faça miar mais alto!",
  "Isso não é um parque de diversões!",
  "Pssst! Você se esqueceu da senha?",
  "Um momento... isso é um acesso restrito!",
];
